[env:tasmota32-zigbee-tcp]
extends = env:tasmota32-zigbeebridge
build_flags =
  ${env:tasmota32-zigbeebridge.build_flags}
  -DUSE_TCP_BRIDGE
; kein Ethernet erstmal:
;  -DUSE_ETHERNET
;  -DUSE_LAN8720
