name: Build TCP Zigbee
on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PlatformIO
        run: pip install -U platformio

      # Optional: einmalig aktivieren, wenn Pakete „verklemmt“ sind
      #- name: PlatformIO purge (optional)
      #  run: pio pkg purge --global --yes || true

      - name: Clean PlatformIO packages cache
        run: rm -rf ~/.platformio/packages ~/.platformio/.cache


      - name: Prune PIO caches (sauberer Runner)
        run: pio system prune -f

      - name: Show effective config
        run: pio project config

      - name: Clean + Build
        run: |
          pio run -t clean -e tasmota32-zigbee-tcp
          pio run -e tasmota32-zigbee-tcp


      #- name: Build env tasmota32-zigbee-tcp
      #  run: |
      #    pio run -t clean -e tasmota32-zigbee-tcp
      #    pio run -e tasmota32-zigbee-tcp

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: tasmota32-zigbee-tcp
          path: .pio/build/tasmota32-zigbee-tcp/firmware.bin
